import pandas as pd
df = pd.read_excel("students.xlsx")
print("========== 1- Rows ==========")
print(df.head())
print("\n==========2- Dataset Information ==========")
print(df.info())
print("\n==========3- Statistical Summary ==========")
print(df.describe())
print("\n==========4- Missing Values ==========")
print(df.isnull().sum())
print("\n==========5- Duplicate Rows ==========")
print(df[df.duplicated()])
print("\n==========6- Invalid Grades (>100) ==========")
print(df[df["Grade"] > 100])
df.loc[df["Name"] == "Youssef", "Grade"] = 84
df.loc[df["Name"] == "Khaled", "Attendance"] = 83
df.loc[df["Name"] == "Laila", "Grade"] = 95
df = df.drop_duplicates()
print("\n==========7-Cleaned Data ==========")
print(df)
average_grade = df["Grade"].mean()
print("\nAverage Grade:")
print(average_grade)
best_student = df.loc[df["Grade"].idxmax()]
print("\nBest Student:")
print(best_student)
department_average = df.groupby("Department")["Grade"].mean()
print("\nAverage Grade by Department:")
print(department_average)
best_department = department_average.idxmax()
print("\nBest Department:")
print(best_department)
df.to_csv("clean_students.csv", index=False)
print("\nCleaned file saved successfully.")