import pandas as pd
df = pd.read_csv("lab8/titanic_data.csv")
print(df.head())
df.info()
print("Duplicates:", df.duplicated().sum())
df = df.drop_duplicates()
print("Shape:", df.shape)
print(df.isnull().sum())
print(df["age"].describe())
df["age"] = df["age"].fillna(df["age"].median())
print(df["embarked"].value_counts())
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])
df = df.drop(columns=["deck"])
df["embark_town"] = df["embark_town"].fillna(df["embark_town"].mode()[0])
print(df.isnull().sum())
print("Total Fare:", df["fare"].sum())
print("Total Survivors:", df["survived"].sum())
